# Spring Application Name
spring.application.name=admin-server

# Server Port
server.port=7090

# Management Endpoints Web Exposure
management.endpoints.web.exposure.include=*

# Management Endpoint Health Details
management.endpoint.health.show-details=always